Iter18
havilcorp/yandex-go-musthave-metrics-tpl pull request #7
Opened 2024-04-07 14:31 UTC by havilcorp

2024-04-07 14:53 UTC, havilcorp commented
После дипломного проекта накопились дела, не думал что сразу же будет сложный спринт. Много времени ушло на переделку структуры проекта, достижения покрытия тестами 40%, разобраться с профилированием и бенчмарками, понять что от меня хотят) Плюс всю теорию по паттернам выписывал отдельно для дальнейшего изучения и заучивания.

2024-04-09 20:02 UTC, tmvrus requested changes
есть проблемы

2024-04-09 20:02 UTC, tmvrus commented on cmd/agent/main.go
> +	// conf, err := config.ConfigFactory("agent")
закоменченный код в рабочем проекте лучше не оставлять - дурной тон

2024-04-09 20:02 UTC, tmvrus commented on cmd/agent/main.go
> +		return
тут больше подойдет log.Fatal

2024-04-09 20:02 UTC, tmvrus commented on cmd/agent/main.go
> +	chDone <- struct{}{}
канал закрывается два раза, это паника
этот код вообще проверялся?

2024-04-09 20:36 UTC, havilcorp commented on cmd/agent/main.go
> +	chDone <- struct{}{}
Код в рабочем состоянии, не думал что каналы в таком случае могут вызвать панику, теперь знаю, спасибо.

2024-04-10 15:10 UTC, tmvrus approved these changes

2024-04-16 22:11 UTC, merged